# Generated by Django 5.1.5 on 2025-02-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_description', models.TextField(max_length=1000)),
                ('company_status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Finace', 'Finace'), ('Educational', 'Educational'), ('Hardware', 'Hardware')], default='IT', max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
